### ISSUE TITLE
Fatal Error: Can not push to upstream

### ISSUE THREAD

**Issue by prescottprue** [vojtajina/grunt-bump#112]
When grunt-bump is trying to commit I received this error message:

```
Running "bump" task
>> Version bumped to 1.0.0-a.1 (in package.json)
>> pkg's version updated
>> Version bumped to 1.0.0-a.1 (in bower.json)
>> Committed as "[RELEASE] Release v1.0.0-a.1"
>> Tagged as "v1.0.0-a.1"
Fatal error: Can not push to upstream:
  warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It was remedied by setting the push.default:
`git config --global push.default simple`
Then switching the pushTo parameter from `'upstream'` to `'origin'` (which is obviously the name of the remote I would like to pushTo). 

It might be good to clarify that this parameter means which **remote** you would like to push to and its default value should probably be **origin**. All of this does not really matter if you use the -u command on your first push (i.e. `git push -u origin master`) but if the upstream is not set, then this error can arise.

I LOVE THIS PACKAGE!

**Comment by eddiemonge** [comment]
Convention for git when working with remotes is that `origin` is your cloned copy of a `master` (upstream) repo that you usually `git remote add upstream remoteRepoUrl`. So you do your work in your local branches, push to your `origin` remote and then do a pull request from there. You normally do a `pull (--rebase) upstream master` to pull in the latest changes. Since releases should happen from the `master` repo, the bump, tag and push should go to `upstream`.
