### ISSUE TITLE
Exclude from processing or change only specified fields

### ISSUE THREAD

**Issue by skobkin** [vojtajina/grunt-bump#113]
I using grunt-bump for browser extension.

There is a problem: it contains `manifest.json` which I want to bump too. But `grunt bump` changes not only `"version": "1.18.8"` field, but `"manifest_version": 2` too. Obviously this behavior [breaks extension](https://bitbucket.org/skobkin/chrome_point_plus/commits/8fccbe9137072a790dc7b8365a6ce897449e64a3?at=master#Lchrome_point_plus/manifest.jsonT2).

I think it's good to be to add optional parameter to specify which fields in the each file `grunt bump` must change.

**Comment by skobkin** [comment]
PR 76 does not do exactly what I think it must do but in my project specifically it may help.

**Comment by eddiemonge** [comment]
the regex needs to be stricter i believe for non-JSON files and switched to https://github.com/vojtajina/grunt-bump/issues/119 for JSON files

**Comment by eddiemonge** [comment]
This should be fixed maybe. Please let me know if its not.
