### ISSUE TITLE
Examples for `bump-only` and `bump-commit` don't work

### ISSUE THREAD

**Issue by alexilyaev** [vojtajina/grunt-bump#122]
Seems like these are wrong:
```
$ grunt bump-only:minor
$ grunt changelog
$ grunt bump-commit
```
Got this:
```
Alexs-MacBook-Pro:nc-reveal alex$ grunt bump-commit --dry-run

jit-grunt: Plugin for the "bump-commit" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "bump-commit" failed. Use --force to continue.

Aborted due to warnings.
```
Checking the code, looks like it should be used as:
```
grunt bump:patch:bump-only --dry-run
```
Which works.

**Comment by eddiemonge** [comment]
No the problem is you are using [jit-grunt](https://www.npmjs.com/package/jit-grunt#static-mappings) which needs to have the commands mapped. I use the example everyday without problem.

**Comment by rekomat** [comment]
Mapping the task names: 

```
require('jit-grunt')(grunt, {
  'bump-only': 'grunt-bump', 
  'bump-commit': 'grunt-bump'
});
```

Reference: [jit-grunt static mapping](https://github.com/shootaroo/jit-grunt#static-mappings)

**Comment by kitsguru** [comment]
I am using grunt-bump with jit-grunt & grunt 1.0.1 and getting an error for bump-only. bump by itself works fine.

gruntfile.js
````
    require('jit-grunt')(grunt)({
       'bump-only': 'grunt-bump',
       'bump-commit': 'grunt-bump',
       customTasksDir: 'grunt-tasks'
    });
````
Error is
````
jit-grunt: Plugin for the "bump-only" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "bump-only" failed. Use --force to continue.
````

I have tried several variations of the static mappings but everyone results in the same error. I am using the example grunt-bump configuration.

**Comment by eddiemonge** [comment]
Can you open this as a new issue please?

**Comment by kitsguru** [comment]
opened as new issue #183
