### ISSUE TITLE
How to generate build files before commiting

### ISSUE THREAD

**Issue by uglymunky** [vojtajina/grunt-bump#130]
Hi, does `grunt-bump` support having a step for generating build files after the package.json file is updated but before the commit is made?  My current workflow for releasing a new version goes like this:

* Make sure my git stage is clean
* Make sure I'm on master
* bump the version (update package.json + bower.json, etc..)
* run some kind of build task that generates `/dist` files
* add changes
* commit changes
* create tag
* push commit + tags

How would I go about recreating this [currently manual] work flow to a more automated flow using grunt-bump?

Thanks for your help!

**Comment by eddiemonge** [comment]
grunt bump-only:minor 
grunt changelog
grunt bump-commit

**Comment by uglymunky** [comment]
d'oh, I think I saw that in the docs too, just didn't register.  Thank you.
