### ISSUE TITLE
Add custom Commit Message

### ISSUE THREAD

**Issue by amolc** [vojtajina/grunt-bump#134]
Hello Guys, 

I have been using the grunt bump very nicely to package my files. One major setback is that I am unable to send a custom commit message. Is there any way we can manage this.

**Comment by eddiemonge** [comment]
What is the custom commit message message for? Are you talking about a different one every time? If not, there is the `commitMessage` option

**Comment by amolc** [comment]
Hello,

Yes, I like we can bump the versions. But the issue happens when we want to
send a custom message.

Best regards

Amol Chawathe


[image: Logo fountaintechies.jpg]
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsd78r-VcV_Fz65jBNnW5wvxsz56dPqrf2LNPY402?t=http%3A%2F%2Fwww.fountaintechies.com%2F&si=5044900185767936&pi=30bc6aa5-5999-49ee-830a-32d04484f4f8>

The Globe,10th Floor

100 Cecil St

Singapore 069532

phone: +65 81457305

email: amol.chawathe@fountaintechies.com

web: www.fountaintechies.com
<http://t.signaleuna.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsd78r-VcV_Fz65jBNnW5wvxsz56dPqrf2LNPY402?t=http%3A%2F%2Fwww.fountaintechies.com%2F&si=5044900185767936&pi=30bc6aa5-5999-49ee-830a-32d04484f4f8>

**Comment by listao** [comment]
@amolc, Maybe you could try looking to setting a custom `grunt.option` in combination with `grunt-shell`? So you could so something like: 

**Gruntfile.js**
```
grunt.initConfig({
    bump: {
       //options goes here...
       commit: false
   }
    shell: {
        commit: {
           command: 'git commit -am "' + grunt.option('msg') + '"' 
       }
    }
})

grunt.registerTask('build', 'Build stuff', function(msg) {
   //Set the option
   grunt.option('msg', msg);   
   //Run the task.
   grunt.task.run('bump-only', 'shell:commit');
});
```

**Terminal**
```
grunt build --msg="Hello world. This is the first commit"
```

**Comment by eddiemonge** [comment]
closing due to not providing a great use case
