### ISSUE TITLE
How can I createTag and push after changelog?

### ISSUE THREAD

**Issue by stevemao** [vojtajina/grunt-bump#136]
Sorry if someone else already brought this up...

Can we do something like `bump-tag` and `bump-push`?

References: 
https://github.com/karma-runner/karma/blob/master/Gruntfile.coffee#L145
https://github.com/btford/grunt-conventional-changelog/blob/master/Gruntfile.js#L27-L28
If we can achieve this, can we add it to the doc?

**Comment by eddiemonge** [comment]
like ths at the bottom of the readme?

> $ grunt bump-only:minor
> $ grunt changelog
> $ grunt bump-commit

**Comment by stevemao** [comment]
Sorry, when I opened this issue I couldn't tag or push properly for some reason. I tried again with a dummy repo and it works now. Can't remember what I have done wrong. Will reopen if I fail next time when I release grunt-conventional-changelog
