### ISSUE TITLE
Update to latest semver module

### ISSUE THREAD

**Issue by pdehaan** [vojtajina/grunt-bump#137]
Per https://nodesecurity.io/advisories/semver_redos

> Patched: [>=4.3.2](https://github.com/npm/node-semver)

This will cause issues for anybody who uses something like [**nsp**](https://www.npmjs.com/package/nsp) to monitor for potentially risky modules.

**Comment by eddiemonge** [comment]
pr welcome

**Comment by eddiemonge** [comment]
updated in https://github.com/vojtajina/grunt-bump/commit/f0f04efd250f430bb165e5efc8ec8731cf513ded
