### ISSUE TITLE
Error when bumping minor version

### ISSUE THREAD

**Issue by AuspeXeu** [vojtajina/grunt-bump#139]
I am left with this error message when I call using the latest version.

`grunt bump`

```bash
module.js:338
    throw err;
          ^
Error: Cannot find module './lexer'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    [...]
```

**Comment by eddiemonge** [comment]
Are you sure thats from this module? What makes you think that it is? Have you tried `npm install && npm update` before running?

**Comment by AuspeXeu** [comment]
Well I deleted all node modules and reinstalled it. Now it works like a charm. Thanks.
