### ISSUE TITLE
Dry-run + separate bump-only and commit gives wrong version number

### ISSUE THREAD

**Issue by pimterry** [vojtajina/grunt-bump#145]
Small bug, but might be of interest.

If my version is currently set to 0.0.3, and I run a task something like:

```
grunt bump:bump-only bump:commit-only --dry-run
```

I should see the version bumped to 0.0.4, and that version then pushed. Instead I see:

```
Running "bump::bump-only" (bump) task
Running grunt-bump in dry mode!
>> bump-dry: Version bumped to 0.0.4 (in app/manifest.json)

Running "bump::commit-only" (bump) task
Running grunt-bump in dry mode!
>> bump-dry: git commit app/manifest.json -m "Release 0.0.3"
>> bump-dry: git tag -a v0.0.3 -m "Version 0.0.3"
>> bump-dry: git push upstream && git push upstream --tags
```

I.e. the version is bumped to 0.0.4, but the commit message and tags all reference 0.0.3. Presumably this is because the version gets reloaded from the manifest between these tasks, assuming that it's changed, but in a dry run it doesn't. Doesn't break anything obviously, but it did make me worry for a few minutes checking that it really was intended to commit with the new version number, not the previous one!

**Comment by eddiemonge** [comment]
fixed in 0.4.0
