### ISSUE TITLE
feat: option to get version number from latest git tag

### ISSUE THREAD

**Issue by vishwanath-to** [vojtajina/grunt-bump#146]
How about a option `useLatestTag` for getting version number from latest git tag and bumping it as per the options provided. 

You can get latest tag with `git describe $(git rev-list --tags --max-count=1)`. I may submit a pull request with the changes if you are interested in adding this option.

**Comment by eddiemonge** [comment]
Does that get the latest numerical tag or the latest pushed tag or what?

Regardless, I am not sure of the use here since if all you are bumping is the git version, you can use npm version for that.
