### ISSUE TITLE
How do you use this with npm shrinkwrap?

### ISSUE THREAD

**Issue by adamsilver** [vojtajina/grunt-bump#152]

**Comment by eddiemonge** [comment]
What do you mean?

**Comment by eddiemonge** [comment]
@adamsilver ^^

**Comment by adamsilver** [comment]
Sorry, for lack of description.  What I mean is: if say I wanted to bump the version number in package.json, and *before* it commits to github, generate the npm-shrinkwrap.json file to match the version of the package.json, how do I do that?

**Comment by eddiemonge** [comment]
No idea. Never used npm's shrinkwrap.

**Comment by eddiemonge** [comment]
You could use bump-only, do the shrinkwrap stuff and then bump-commit. Like in the readme:

```
$ grunt bump-only:minor
$ grunt changelog
$ grunt bump-commit
```

**Comment by adamsilver** [comment]
No worries.  We have used our own non script now.  Thanks for replying.
