### ISSUE TITLE
Cannot push to origin: error: unknown option 'abbrev-ref'

### ISSUE THREAD

**Issue by rainabba** [vojtajina/grunt-bump#153]
While trying to use `grunt bump:patch`, I get that error. My task is:

```
bump: {
	options: {
		files: ['package.json'],
		commitFiles: ['package.json'],
		pushTo: 'origin'
	}
},
```

What's going on?

**Comment by eddiemonge** [comment]
What version of git are you using?

**Comment by rainabba** [comment]
2.5.0.windows.1

**Comment by jdiamond** [comment]
The issue on Windows is the backticks/subshell on this line:

https://github.com/vojtajina/grunt-bump/blob/14c48e552b87064cb43738e5894b9ba9d0852146/tasks/bump.js#L225

`child_process.exec()` executes commands with `sh -c` on Unixes (which does support subshells). On Windows, it executes commands with `cmd.exe /c` (which does not support subshells).

**Comment by eddiemonge** [comment]
any clue how to fix that?

**Comment by fr33kvanderwand** [comment]
Have the same Problem (git version: 1.8.3.msysgit.0), tried the fix from jdiamond and it works fine.
