### ISSUE TITLE
getting a error when running grunt-bump on master

### ISSUE THREAD

**Issue by coldpour** [vojtajina/grunt-bump#154]
Here's the error I was getting

    error: dst ref refs/heads/master receives from more than one src.
    error: failed to push some refs to '/Users/mholm/projects/burro'

I tried running with --dry-run for debugging

    % grunt bump --dry-run
    Running "bump" task
    Running grunt-bump in dry mode!
    >> bump-dry: Version bumped to 12.8.3 (in package.json)
    >> pkg's version updated
    >> bump-dry: git commit package.json CHANGELOG.md -m "Release v12.8.3"
    >> bump-dry: git tag -a v12.8.3 -m "Version 12.8.3"
    >> bump-dry: git push origin master `git rev-parse --abbrev-ref HEAD`  && git push origin master v12.8.3

It looks like the problem is that `git rev-parse --abbrev-ref HEAD` returns "master" when you're on the master branch. So it's trying to push master and master to master and having a bad time. It looks like [this commit](https://github.com/vojtajina/grunt-bump/commit/dc5a90e58775533b38c7c7ccb3536ea18a77b91a) was where this broke.

**Comment by eddiemonge** [comment]
If `git rev-parse --abbrev-ref HEAD` returns master then the command should be `git push origin master &&`. What is your `pushTo` option set to?

**Comment by gumallett** [comment]
I had the same issue and had to revert back to 0.3.1

**Comment by coldpour** [comment]
@eddiemonge, my pushTo is set to 'origin master'. It looks like the readme wants pushTo to be the remote. So I'll set that to be origin and then I should be all set. Thanks!

**Comment by neuquino** [comment]
I had the same issue. Reverting back to 0.3.1 solves the problem.

**Comment by coldpour** [comment]
Just change your pushTo to origin. Or try leaving it unspecified.
