### ISSUE TITLE
Do not push tag if createTag is false

### ISSUE THREAD

**Issue by dloehr** [vojtajina/grunt-bump#157]
[fix: push the new tag, not all tags in repo](https://github.com/vojtajina/grunt-bump/commit/55e0d0b81413b31eda78c55ec1af198d998f55ad), which was first released in 0.3.2, causes the task to fail if ```createTag``` is false, but ```push``` is true.

**Comment by eddiemonge** [comment]
@redbmk ^^

**Comment by redbmk** [comment]
Just created a pull request. @dloehr could you try the fix at 682f03d?
