### ISSUE TITLE
.git folder in a parent directory

### ISSUE THREAD

**Issue by numediaweb** [vojtajina/grunt-bump#159]
The `grunt-bump` by default assumes that the `.git` folder is in the same directory as `package.json` which results:
```
Fatal error: Can not push to upstream:
  fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
In my setup, I put all the node related files/directories in a `.build` directory which contains the `node_modules`, `bower_components`

```
    |-- .build                  # Built code; Node.js dependencies and build config.
    |       |-- node_modules
    |       |-- bower_components
    |       |-- Gruntfile.js
    |       |-- package.json
    |-- .git                     # The repository data
    |-- .src                    # Front-end source code (+ browser dependencies)
    |       |-- fonts
    |       |-- images
    |       |-- scripts
    |       |-- scss
    |-- www                     # PHP core code
    |   |-- assets              # This folder is automatically generated by Grunt.
    |   |-- includes            # Core PHP files and dependency libraries.
    |       |-- lib
```
Would be great to have an option to specify the path to the `.git` folder/repository.

**Comment by eddiemonge** [comment]
That makes things a bit more complicated and I'm not sure would be beneficial to the majority of people. I think it would require a lot more work to accomplish this.

If you are versioning and publishing this to npm then having the package.json in a subfolder should also be causing you problems
