### ISSUE TITLE
Empty pushTo does no longer work

### ISSUE THREAD

**Issue by NicBright** [vojtajina/grunt-bump#160]
Since recent versions it is no longer possible to set pushTo to '' to have git decide where to push to (yes, I really liked it a lot that the resulting push command was "git push && git push --tags").

Setting this to '' makes the config universal and work across projects. Also, I consider it to be an anitpattern to specify the name of the "origin" in the config, as the name is individual to each developers machine and I do not want to enforce names such as "origin" or "upstream".

**Comment by eddiemonge** [comment]
you can override the default name using the `--pushTo=` cli option. As to not having a name, it was changed in this commit: https://github.com/vojtajina/grunt-bump/commit/dc5a90e58775533b38c7c7ccb3536ea18a77b91a

**Comment by NicBright** [comment]
Exactly. But setting --pushTo='' is the same as setting pushTo to '' (empty string) and will not work. This clearly is a regression imho. Unless you say that you don't want to support the use-case "let git decide".

**Comment by eddiemonge** [comment]
this was a bug before but ill push a new version as a feature. see 2140be2

**Comment by NicBright** [comment]
Ok thanks a lot for the quick change. Unfortunately, it does no longer push the tags.
Previously it did a "git push && git push --tags", now it only does a "git push".

**Comment by eddiemonge** [comment]
you could always add an extra grunt step that pushes the tags specifically.
