### ISSUE TITLE
Multiple files with different regExp

### ISSUE THREAD

**Issue by SiamKreative** [vojtajina/grunt-bump#161]
Hi there,

Is it possible to have multiple sub-task with a specific regex for each files? I mean something like this:
```javascript
bump: {
	packageJson: {
		options: {
			files: ['package.json']
		}
	},
	pluginConstant: {
		options: {
			regExp: 'define\\(\\s*\'WR_VERSION\',\\s*\'',
			files: ['plugin-reviews.php']
		}
	},
	stableTag: {
		options: {
			regExp: 'Stable tag:\\s+',
			files: ['readme.txt']
		}
	}
},
```

For my WordPress plugin, I'm currently using https://github.com/kswedberg/grunt-version, which works well for version bumps, but it doesn't handle git tag/commit/release/push.

Cheers

**Comment by eddiemonge** [comment]
Its like you didnt even look at the open issues before opening this, I mean literally the first issue in the tracker is what you are asking for: 

![issues](https://cloud.githubusercontent.com/assets/127535/10254551/587a2208-68f9-11e5-91ee-f3ed663752e8.png)

**Comment by SiamKreative** [comment]
Thanks Eddie. Looks like I missed that one.
