### ISSUE TITLE
x.y.z.a format for setversion?

### ISSUE THREAD

**Issue by dlwhiteman** [vojtajina/grunt-bump#163]
Hi,

We have a need to set version numbers with a higher level of granularity.  We would like to set an explicit version with setversion that includes 4 parts instead of 3.  Our releases look like x.y.z, and then we like to append a build number.  So what we'd like to support is 0.2.0.234 as an example.  Can that change be implemented?

Thanks!

**Comment by eddiemonge** [comment]
`options.prereleaseName` but it will tag it with 0.0.0-prname as that it is how it is done in semver. You could always use `grunt bump --setversion=2.0.1` but then don't expect it work properly anymore if you don't use a valid semver tag.
