### ISSUE TITLE
Bumping at -0 prerelease

### ISSUE THREAD

**Issue by mikepc** [vojtajina/grunt-bump#171]
version = "1.2.2"
grunt bump:prerelease

When there is no prerelease or prerelease == "0" I get the error: Fatal error: Can not find a version to bump in package.json 

version = "1.2.2-1"
grunt bump:prerelease
Everything works :)

**Comment by eddiemonge** [comment]
What version of this are you using?

**Comment by eddiemonge** [comment]
Works fine for me.
