### ISSUE TITLE
Version 0.7.2 introduced somewhat breaking changes

### ISSUE THREAD

**Issue by liorch88** [vojtajina/grunt-bump#180]
The latest version (0.7.2) broke my build due to some breaking changes (https://github.com/vojtajina/grunt-bump/commit/0965945f298e275df971447c1a9dfb7fb0144814)
Seems grunt-bump now requires grunt >=1 as a peer dependency, and since I'm still using grunt 0.4 (which is also required by the other grunt plugins I'm using) running `npm install` breaks.
I think this pretty much makes it a breaking change so maybe it would be best to revert the changes and release it again as 1.0.0 or something.
It also makes more sense that a plugin which is versioned as 1.x, matches grunt 1.x.

**Comment by simonkontschak** [comment]
Hi together, 
I have the same trouble which is related to the new grunt depencency as @liorch88  mentioned.
The general problem is, that some libraries are not compatible to 1.x yet. To be able to upgrade grunt-dependend librarires, grunt recommends library-distributors to depend on grunt using "grunt": ">= 0.4.0" [(Grunt Changelog - recommendation).](https://github.com/gruntjs/grunt/blob/master/CHANGELOG)

@vojtajina Would it be possible to change the peerDependency to grunt to be compatible with "grunt": "grunt": ">= 0.4.0"?

**Comment by acjohnso25** [comment]
+1.  My project depends on grunt-bump ^0.7.0.  Over the weekend, my project broke, but nothing changed in my project.  This is pretty much the textbook definition of "breaking change" IMHO.  :)

**Comment by soycode** [comment]
Another :+1: on this (specifically the peerDependency >= 0.4.0 approach) - thanks!

**Comment by johnyb** [comment]
If you rely on grunt 1.0 features, please do a bump:minor, not a bump:patch. I thought, grunt-bump was about semver, so please stick to it.

**Comment by jml6m** [comment]
+1, this is very annoying, ended up just removing grunt-bump for now

**Comment by cristian-sima** [comment]
+1

**Comment by eddiemonge** [comment]
Published 0.8.0 with the changes the grunt changes.
Published 0.7.3 with the reverted changes so nothing should break

**Comment by eddiemonge** [comment]
> It also makes more sense that a plugin which is versioned as 1.x, matches grunt 1.x.

Actually no. The plugin is independent of grunts version

**Comment by simonkontschak** [comment]
Thanks a lot for solving that fast.
