### ISSUE TITLE
 "bump-only" task not found with jit-grunt static mapping

### ISSUE THREAD

**Issue by kitsguru** [vojtajina/grunt-bump#183]
I am using grunt-bump v0.8.0 with jit-grunt v0.10.0 & grunt 1.0.1 and getting an error for bump-only and bump-commit. bump by itself works fine.

gruntfile.js
````
    require('jit-grunt')(grunt)({
       'bump-only': 'grunt-bump',
       'bump-commit': 'grunt-bump',
       customTasksDir: 'grunt-tasks'
    });
````

Error is
````
jit-grunt: Plugin for the "bump-only" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "bump-only" failed. Use --force to continue.
````

I have tried several variations of the static mappings but everyone results in the same error. I am using the example grunt-bump configuration.

**Comment by eddiemonge** [comment]
Have you asked on the jit-grunt repo?

**Comment by kitsguru** [comment]
No, because I found a previous issue here and I used the supplied answer. I will however do so now.
