### ISSUE TITLE
As a developer, I want to create an actual GitHub release so that when I publish to NPM and Bower Registries the latest version match the latest GitHub release.

### ISSUE THREAD

**Issue by pouncilt** [vojtajina/grunt-bump#186]
The current version of grunt-bump v0.8.0 does only creates tags on GitHub.  I would like it to also create a release on GitHub.

**Acceptance Criteria:**

- A new release should be created on GitHub after running the 'grunt bump' command using the current configuration object for v0.8.0.

**Current Configuration Object for v0.8.0**
`bump: {
            options: {
                files: ['package.json', 'bower.json'],
                updateConfigs: ['pkg'],
                commit: true,
                commitMessage: 'Release v%VERSION%',
                commitFiles: ['-a'],
                createTag: true,
                tagName: 'v%VERSION%',
                tagMessage: 'Version %VERSION%',
                push: true,
                pushTo: 'origin',
                gitDescribeOptions: '--tags --always --abbrev=1 --dirty=-d',
                globalReplace: false,
                prereleaseName: false,
                metadata: '',
                regExp: false
            }
        }`

**Comment by Psykoral** [comment]
:+1: I agree, an official "release" would be ideal over just a tag for certain users, myself included. 

https://developer.github.com/v3/repos/releases/#create-a-release

**Comment by eddiemonge** [comment]
Releases are more subjective and extend the scope of this too much. When I say subjective, I mean that the release notes could be different, there might need to be different processes, etc. There are too many variables. Also, if doing a GH release, why not also npm publish and bower publish? Like I said, it adds too much complexity. You could create another module that runs after this to do that if you want.
