### ISSUE TITLE
Appveyor.yml conflict

### ISSUE THREAD

**Issue by ctjhoa** [vojtajina/grunt-bump#190]
Appveyor concat the build number after the version number.
(see https://www.appveyor.com/docs/appveyor-yml)

If you `grunt bump` an `appveyor.yml` this will happen:
```bash
% git diff appveyor.yml
diff --git a/appveyor.yml b/appveyor.yml
index bd780a8..6c00031 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -1,4 +1,4 @@
-version: 0.4.3.{build}
+version: 0.4.4{build}
```

As you can see the final dot is removed by the bump because of the default RegExp (https://github.com/vojtajina/grunt-bump/blob/master/tasks/bump.js#L49)

If I remove this dot:
```
    var VERSION_REGEXP = opts.regExp || new RegExp(
      '([\'|\"]?version[\'|\"]?[ ]*:[ ]*[\'|\"]?)(\\d+\\.\\d+\\.\\d+(-' +
      opts.prereleaseName +
      '\\.\\d+)?(-\\d+)?)[\\d||A-a|.|-]*([\'|\"]?)', 'i'
     ------------------------------^
    );
```
I get the expected behavior and the final dot in `appveyor.yml` is preserved.

I know that I can override the RegExp but it has limitation for now (see #189)
I just want to signal this case to get a clear answer if the dot is intended and to help anyone in my case.

**Comment by eddiemonge** [comment]
The dot makes it a not-valid semver range. Anything after the 3 segment should be joined with a dash, not a dot. If you have to support a custom regex, then like you said, you can pass it in.
