### ISSUE TITLE
bump-commit ignores created files

### ISSUE THREAD

**Issue by svenkuhn** [vojtajina/grunt-bump#206]
Hello.
It seems, that bump-commit ignores files, that where created in the same task.
I'm trying to increment the version. Then the main task is executed and after that everything should be commited.
But thats not working correctly. All files, that were created during the task in my dist-folder are excluded from the commit.
There is a .gitignore file but this only excludes the node_modules/

My config:
```
...
bump: {
    options: {
        commit: true,
        push: false,
        createTag: true,
        prereleaseName: 'rc',
        commitFiles: ['-a'],
        updateConfigs: ['pkg']
    }
 },
...


My Task
`grunt.registerTask('prerelease', ['bump-only:prerelease', 'dist', 'bump-commit']);

**Comment by eddiemonge** [comment]
So you are saying your package.json file isn't getting committed?

**Comment by svenkuhn** [comment]
No, all the new files that were created in my dist-folder during the task are not commited.

So this is a simple version my gruntfile.

What should happen here?
1. Update the version
2. Create a css-file in my dist-folder from a less-file in my src-folder
3. Commit everything

The problem is, that the css-file that was created during this task is not committed.

`module.exports = function(grunt) {
    'use strict';

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        distPath: 'dist/<%= pkg.name %>/',

        clean: {
            dist: ['<%= distPath %>/']
        },

        less: {
            dist: {
                files: {
                    '<%= distPath %>css/<%= pkg.name %>.<%= pkg.version %>.min.css': 'src/less/main.less',
                }
            }
        },
        bump: {
            options: {
                commit: true,
                push: false,
                createTag: true,
                prereleaseName: 'rc',
                commitFiles: ['-a'],
                updateConfigs: ['pkg']
            }
         },
    });

    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.loadNpmTasks('grunt-bump');

    grunt.registerTask('dist', ['clean:dist', 'less:dist']);
    grunt.registerTask('prerelease', ['bump-only:prerelease', 'dist', 'bump-commit']);

};
`

**Comment by eddiemonge** [comment]
You will need to add an additional task to `dist` to stage the untracked files to git. `-a` only adds tracked files.
