### ISSUE TITLE
Add tags for only certain types of version

### ISSUE THREAD

**Issue by andywillis** [vojtajina/grunt-bump#84]
I might want to only make a tag for a certain type of release. Would that be possible?

So instead of `createTag: true,` it might be `createTag: ['major'],` or `createTag: ['major', 'minor'],`?

**Comment by rysilva** [comment]
Firstly, `grunt.option('createTag') || true` returns true if you have set `--createTag=false`.  

Anyway, this is not how I expected to be able to customize these tasks.  I would have expected to do something like this:

    bump: {
        options: {
            createTag: true,
            pushTo: 'origin'
        },
        prerelease: {
            createTag: false
        }
    }

Or maybe 

    bump: {
        options: {
            createTag: true,
            pushTo: 'origin'
        },
        custom: {
            createTag: false,
            type: "prerelease"
        }
    }

**Comment by eddiemonge** [comment]
> Firstly, grunt.option('createTag') || true returns true if you have set --createTag=false.

Thats a grunt bug then and should be opened at grunt.

This isn't a multi-task plugin so there are no targets

**Comment by rysilva** [comment]
`false || true` is true

I've found a different solution for my versioning needs, but I do think multiple tasks would make this plugin more useful.  Thanks for the replies.

**Comment by blowsie** [comment]
@rysilva,  you found a small issue in the example, but its not hard to fix it .
`typeof grunt.option('createTag') !== 'undefined' ? grunt.option('createTag') : true`

**Comment by blowsie** [comment]
@eddiemonge , I know this is an old thread, but I tested the above approach, and it does not work when using `bump-commit` 

eg:
```
grunt.registerTask('release', function(target) {
  if (target === 'prerelease') {
    grunt.option('createTag', false);
  }

  grunt.task.run('bump-commit');
});
```

Is there a way round this?
