### ISSUE TITLE
Test run feature

### ISSUE THREAD

**Issue by AoDev** [vojtajina/grunt-bump#89]
Would be nice to have a "test run" option which would run the task without doing anything actually.

I setup everything in my repo but I'd like to test my configuration without creating an actual release.

It would log every step in the console and that way we could spot an error in the config.

Thank you for your work :)

**Comment by niksy** [comment]
:+1: for dry run feature (something like https://github.com/geddski/grunt-release/ supports)

**Comment by AoDev** [comment]
@eddiemonge @swenzel I haven't tried it yet but I wanted to thank you for adding this feature :)

**Comment by eddiemonge** [comment]
thank @swenzel . I didn't do anything really
