### ISSUE TITLE
Support grunt bump:minorprerelease

### ISSUE THREAD

**Issue by wrumsby** [vojtajina/grunt-bump#94]
I'd like to be able to bump, e.g. `2.9.0` to `2.10.0-0` with a single task, e.g. `grunt bump:minorprerelease`.

At present this doesn't seem to be possible.

**Comment by eddiemonge** [comment]
I think this should work with an updated semver that better supports prereleases

**Comment by micahgodbolt** [comment]
+1 to this. Can't currently transition from previous minor version to new prerelease.

2.9.9 bump:prerelease = 2.9.9-1
2.9.9 bump:patch = 2.9.10
2.9.9 bump:minor = 2.10.0 + bump:prerelease = 2.10.1-1

**Comment by eddiemonge** [comment]
thats a bug in the old semver. its been fixed since but semver here hasn't been updated as it would require testing everything. keep meaning to do it at some point
